from typing import Dict

tiny_imagenet_classes = [
    "pez dorado",
    "salamandra europea",
    "rana toro",
    "rana de cola",
    "caimán americano",
    "boa constrictor",
    "trilobite",
    "escorpión",
    "viuda negra",
    "tarántula",
    "ciempiés",
    "ganso",
    "koala",
    "medusa",
    "coral cerebro",
    "caracol",
    "babosa",
    "babosa marina",
    "langosta americana",
    "langosta espinosa",
    "cigüeña negra",
    "pingüino rey",
    "albatros",
    "dugongo",
    "chihuahua",
    "yorkshire terrier",
    "golden retriever",
    "labrador retriever",
    "pastor alemán",
    "caniche estándar",
    "atigrado",
    "gato persa",
    "gato egipcio",
    "puma",
    "león",
    "oso pardo",
    "mariquita",
    "mosca",
    "abeja",
    "saltamontes",
    "bastón",
    "cucaracha",
    "mantis",
    "libélula",
    "monarca",
    "mariposa azufre",
    "pepino de mar",
    "cobaya",
    "cerdo",
    "buey",
    "bisonte",
    "ciervo americano",
    "gacela",
    "camello árabe",
    "orangután",
    "chimpancé",
    "babuino",
    "elefante africano",
    "panda menor",
    "ábaco",
    "toga académica",
    "altar",
    "delantal",
    "mochila",
    "barnister",
    "barbería",
    "granero",
    "barril",
    "balón de baloncesto",
    "bañera",
    "carrito de playa",
    "faro",
    "vaso de precipitados",
    "botella de cerveza",
    "bikini",
    "prismáticos",
    "casa para pájaros",
    "pajarita",
    "latón",
    "escoba",
    "cubo",
    "balatren",
    "carnicería",
    "vela",
    "cañón",
    "cárdigan",
    "cajero automático",
    "reproductor de CD",
    "cadena",
    "cofre",
    "calcetín navideño",
    "vivienda en acantilado",
    "teclado de ordenador",
    "confitería",
    "descapotable",
    "grúa",
    "presa",
    "escritorio",
    "mesa de comedor",
    "baqueta",
    "mancuerna",
    "mástil de bandera",
    "fuente",
    "vagón de carga",
    "sartén",
    "abrigo de piel",
    "máscara de gas",
    "kart",
    "góndola",
    "reloj de arena",
    "iPod",
    "jinrikisha",
    "kimono",
    "pantalla de lámpara",
    "cortacésped",
    "bote salvavidas",
    "limusina",
    "brújula magnética",
    "mástil de mayo",
    "uniforme militar",
    "minifalda",
    "furgoneta de mudanzas",
    "clavo",
    "cuellosoporte",
    "obelisco",
    "oboe",
    "órgano",
    "parquímetro",
    "teléfono público",
    "valla de estacas",
    "frasco de pastillas",
    "émbolo",
    "poste",
    "furgoneta de policía",
    "poncho",
    "botella de refresco",
    "torno de alfarero",
    "proyectil",
    "saco de boxeo",
    "carrete",
    "refrigerador",
    "control remoto",
    "mecedora",
    "balón de rugby",
    "sandalia",
    "autobús escolar",
    "marcador",
    "máquina de coser",
    "snorkel",
    "calcetín",
    "sombrero",
    "calefactor",
    "telaraña",
    "coche deportivo",
    "puente de arco de acero",
    "cronómetro",
    "gafas de sol",
    "puente colgante",
    "bañador",
    "jeringa",
    "tetera",
    "osito de peluche",
    "paja",
    "antorcha",
    "tractor",
    "arco triunfal",
    "trolebús",
    "torniquete",
    "paraguas",
    "vestidura",
    "viaducto",
    "voleibol",
    "jarra de agua",
    "torre de agua",
    "wok",
    "cuchara de madera",
    "cómic",
    "plato",
    "guacamole",
    "helado",
    "polo de hielo",
    "pretzel",
    "puré de patatas",
    "coliflor",
    "pimiento morrón",
    "champiñón",
    "naranja",
    "limón",
    "plátano",
    "granada",
    "pastel de carne",
    "pizza",
    "pastel de olla",
    "espresso",
    "alpicio",
    "acantilado",
    "arrecife de coral",
    "orilla del lago",
    "costa",
    "bellota",
]


def load_tiny_imagenet_classes() -> Dict[str, str]:
    path = __file__.replace("wnids.py", "wnids.txt")
    classes = {}

    with open(path) as f:
        for line in f:
            wnid, name = line.strip().split("|")
            classes[wnid] = name

    return classes


tiny_imagenet_classes = load_tiny_imagenet_classes()
